//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobmvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_tb
    {
        public int Appln_Id { get; set; }
        public int User_Id { get; set; }
        public int Job_Id { get; set; }
        public string CV { get; set; }
        public System.DateTime Appln_Date { get; set; }
        public string Appln_Status { get; set; }
    }
}
