//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobmvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Reg
    {
        public int Company_Id { get; set; }
        public string Comapany_Name { get; set; }
        public string Company_Address { get; set; }
        public string Company_Email { get; set; }
        public string Company_Phone { get; set; }
        public string Company_State { get; set; }
        public string Company_District { get; set; }
    }
}
