//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobmvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_tb
    {
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public string Job_Title { get; set; }
        public string Job_Desc { get; set; }
        public int Exp_In_Yrs_Needed { get; set; }
        public string Skills_Needed { get; set; }
        public string Job_Location { get; set; }
        public string Job_Salary { get; set; }
        public string Job_Type { get; set; }
        public System.DateTime Last_Date { get; set; }
        public string Job_Status { get; set; }
    }
}
