//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobmvcproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jobmvc_projectEntities : DbContext
    {
        public jobmvc_projectEntities()
            : base("name=jobmvc_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application_tb> Application_tb { get; set; }
        public virtual DbSet<Company_Reg> Company_Reg { get; set; }
        public virtual DbSet<Job_tb> Job_tb { get; set; }
        public virtual DbSet<Login_tb> Login_tb { get; set; }
        public virtual DbSet<User_Reg> User_Reg { get; set; }
        public virtual DbSet<userage> userages { get; set; }
    
        public virtual int sp_appliinsert(Nullable<int> uid, Nullable<int> jid, string cv, Nullable<System.DateTime> appldate, string applstatus)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var appldateParameter = appldate.HasValue ?
                new ObjectParameter("appldate", appldate) :
                new ObjectParameter("appldate", typeof(System.DateTime));
    
            var applstatusParameter = applstatus != null ?
                new ObjectParameter("applstatus", applstatus) :
                new ObjectParameter("applstatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_appliinsert", uidParameter, jidParameter, cvParameter, appldateParameter, applstatusParameter);
        }
    
        public virtual int sp_companyreg(Nullable<int> cid, string cname, string cadd, string cemail, string cphn, string cstate, string cdis)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            var caddParameter = cadd != null ?
                new ObjectParameter("cadd", cadd) :
                new ObjectParameter("cadd", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            var cphnParameter = cphn != null ?
                new ObjectParameter("cphn", cphn) :
                new ObjectParameter("cphn", typeof(string));
    
            var cstateParameter = cstate != null ?
                new ObjectParameter("cstate", cstate) :
                new ObjectParameter("cstate", typeof(string));
    
            var cdisParameter = cdis != null ?
                new ObjectParameter("cdis", cdis) :
                new ObjectParameter("cdis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_companyreg", cidParameter, cnameParameter, caddParameter, cemailParameter, cphnParameter, cstateParameter, cdisParameter);
        }
    
        public virtual int sp_jobinsert(Nullable<int> cid, string jtitle, string jdesc, Nullable<int> expyr, string skills, string jloc, string jsalary, string jtype, Nullable<System.DateTime> lastdate, string jstatus)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jtitleParameter = jtitle != null ?
                new ObjectParameter("jtitle", jtitle) :
                new ObjectParameter("jtitle", typeof(string));
    
            var jdescParameter = jdesc != null ?
                new ObjectParameter("jdesc", jdesc) :
                new ObjectParameter("jdesc", typeof(string));
    
            var expyrParameter = expyr.HasValue ?
                new ObjectParameter("expyr", expyr) :
                new ObjectParameter("expyr", typeof(int));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var jlocParameter = jloc != null ?
                new ObjectParameter("jloc", jloc) :
                new ObjectParameter("jloc", typeof(string));
    
            var jsalaryParameter = jsalary != null ?
                new ObjectParameter("jsalary", jsalary) :
                new ObjectParameter("jsalary", typeof(string));
    
            var jtypeParameter = jtype != null ?
                new ObjectParameter("jtype", jtype) :
                new ObjectParameter("jtype", typeof(string));
    
            var lastdateParameter = lastdate.HasValue ?
                new ObjectParameter("lastdate", lastdate) :
                new ObjectParameter("lastdate", typeof(System.DateTime));
    
            var jstatusParameter = jstatus != null ?
                new ObjectParameter("jstatus", jstatus) :
                new ObjectParameter("jstatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobinsert", cidParameter, jtitleParameter, jdescParameter, expyrParameter, skillsParameter, jlocParameter, jsalaryParameter, jtypeParameter, lastdateParameter, jstatusParameter);
        }
    
        public virtual int sp_logincountid(string una, string pwd, ObjectParameter status)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logincountid", unaParameter, pwdParameter, status);
        }
    
        public virtual int sp_logininsert(Nullable<int> rid, string una, string pw, string utype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", ridParameter, unaParameter, pwParameter, utypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginRegId(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginRegId", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxidlogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxidlogin");
        }
    
        public virtual int sp_userreg(Nullable<int> uid, string na, Nullable<int> ag, string add, string ph, string email, Nullable<int> expinyr, string skills, string res, Nullable<System.DateTime> dob, string status)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var expinyrParameter = expinyr.HasValue ?
                new ObjectParameter("expinyr", expinyr) :
                new ObjectParameter("expinyr", typeof(int));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var resParameter = res != null ?
                new ObjectParameter("res", res) :
                new ObjectParameter("res", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userreg", uidParameter, naParameter, agParameter, addParameter, phParameter, emailParameter, expinyrParameter, skillsParameter, resParameter, dobParameter, statusParameter);
        }
    
        public virtual int sp_userregage(Nullable<int> uid, Nullable<int> ag, string status)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userregage", uidParameter, agParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_companyid_Result> sp_companyid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_companyid_Result>("sp_companyid");
        }
    
        public virtual int sp_jobsearches(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearches", qryParameter);
        }
    }
}
