//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobmvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Reg
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int Exp_In_Yrs { get; set; }
        public string Skills { get; set; }
        public string Resume { get; set; }
        public System.DateTime DOB { get; set; }
        public string User_Status { get; set; }
    }
}
